#include <stdio.h>
#include <stdlib.h>
#include <sys/types.h>


int checkP2(int x);
int *dTob(int n, int l);
int bTod(int a[], int l);


int main() {
    int pgs = 4; // page size
    int ms = 32; // memory size
    int nof = ms / pgs; // number of frames
    int offset_bit = checkP2(pgs); // find out # of bits required for offset
    int m = checkP2(ms); // find out address spaces required in main memory
    int pg_num_bit = m - offset_bit; // find out # of bits required for page number
    int la[] = {8, 4, 3, 2, 15, 18, 25}; // logical addresses generated by the CPU
    int pmt[] = {3, 6, 8, 12, 2}; // page table


    // Output header
    printf("Page size: %d\n", pgs);
    printf("Memory size: %d\n", ms);
    printf("Number of frames required: %d\n", nof);
    printf("Page number bits: %d\n", pg_num_bit);
    printf("Offset bits: %d\n", offset_bit);
    printf("Number of address spaces: %d\n", m);
    printf("Page Table_____\n");


    // Display page table
    for (int i = 0; i < sizeof(pmt) / sizeof(pmt[0]); i++) {
        printf("%d -> %d\n", i, pmt[i]);
    }


    // Calculate physical addresses for each logical address
    int i = 0;
while (i < sizeof(la) / sizeof(la[0])) {

    int logical_address = la[i];

    int page_number = logical_address / pgs;

    int offset = logical_address % pgs;

    if (page_number >= sizeof(pmt) / sizeof(pmt[0])) {
        printf("%d is an invalid page number\n", page_number);
    } else {
        int frame_number = pmt[page_number];
        if (frame_number < nof) {
            int physical_address = (frame_number * pgs) + offset;
            printf("Corresponding physical address of logical address %d: %d\n", logical_address, physical_address);
        } else {
            printf("%d is an invalid physical address\n", (frame_number * pgs) + offset);
        }
    }

    i++;
}



    return 0;
}


int checkP2(int x) {
    int count = 0;
    while (x > 1) {
        x = x >> 1;
        count++;
    }
    return count;
}


int *dTob(int n, int l) {
    static int arr[32];
    int i = 0;

    while (i < l) {
        arr[l - i - 1] = n % 2;
        n = n / 2;
        i++;
    }

    return arr;
}



int bTod(int a[], int l) {
    int decimal = 0;
    for (int i = 0; i < l; i++) {
        decimal += a[i] * (1 << (l - i - 1));
    }
    return decimal;
}

